# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Heidelberger Symposium
email: info@hcwk.de
description: >- # this means to ignore newlines until "baseurl:"
  Der Heidelberger Club für Wirtschaft und Kultur e. V. (HCWK) ist eine unabhängige, überparteiliche und fachübergreifende Studierendeninitiative, die 1988 mit dem Ziel gegründet wurde, die Ausbildung an den Universitäten durch Praxisbezug und interdisziplinären Austausch zu ergänzen.
  Zu diesem Zweck organisiert der Club jährlich ein mehrtägiges Symposium zu einem aktuellen Thema von gesellschaftlicher Relevanz.
  In seinem 30-jährigen Bestehen hat sich das Symposium zu einem festen Bestandteil des akademischen Lebens der Stadt Heidelberg etabliert und leistet damit einen bedeutenden Beitrag zu einer lebendigen Universitätskultur. Es soll ein interdisziplinäres Forum für lebendige und kontroverse Debatten geschaffen werden, um Diskussionskultur zu pflegen und dem Bildungsideal vom ganzheitlichen Menschen näher zu kommen.
  Die Umsetzung des Symposiums ermöglicht es Studentinnen und Studenten theoretisches Wissen mit Praxisbezug zu verbinden. Dabei ist die effektive Zusammenarbeit mit dem Team Voraussetzung und Herausforderung zugleich. Die Vorbereitung einer solchen Großveranstaltung beansprucht die beteiligten Organisatorinnen und Organisatoren über ein ganzes Jahr und bindet sie zeitlich neben dem Studium erheblich ein. Die anfallenden Aufgaben decken ein breites Spektrum an ...
baseurl: "/symposium-neutral/" # the subpath of your site, e.g. /blog
url: "maxiherzog.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
